services:
  - type: web
    name: mailnotifier-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GREEN_API_INSTANCE
        sync: false
      - key: GREEN_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
